version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: irctc-postgres
    environment:
      POSTGRES_USER: irctc
      POSTGRES_PASSWORD: irctc_secret
      POSTGRES_DB: irctc_tatkal
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U irctc -d irctc_tatkal']
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: irctc-redis
    command: >
      redis-server
      --notify-keyspace-events KEA
      --maxmemory 256mb
      --maxmemory-policy allkeys-lru
      --save ""
      --appendonly no
    ports:
      - '6379:6379'
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 5s
      timeout: 5s
      retries: 5

  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: irctc-redis-commander
    environment:
      REDIS_HOSTS: local:redis:6379
    ports:
      - '8081:8081'
    depends_on:
      redis:
        condition: service_healthy

volumes:
  pgdata:
    driver: local
