version: '3.8'

services:
  redis:
    image: redis:7-alpine
    ports:
      - '6379:6379'
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
    networks:
      - irctc-net

  postgres:
    image: postgres:15-alpine
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: irctc
      POSTGRES_PASSWORD: password
      POSTGRES_DB: irctc_dev
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - irctc-net

volumes:
  redis_data:
  postgres_data:

networks:
  irctc-net:
